import { Hono } from 'hono';
import { cors } from 'hono/cors';

interface Env { DB: D1Database; FILES: R2Bucket; APP_ORIGIN: string }
type Vars={user?:User;session?:Session};
type AppEnv={Bindings:Env;Variables:Vars};
type User={id:string;student_id:string|null;name:string;role:string;institution:string|null;stage:string|null;status:string;active_course_id:string|null;email:string|null;representative_active:number};
type Session={id:string;user_id:string;impersonator_user_id:string|null};
const app=new Hono<AppEnv>();
const roles=['Student','Representative Student','Teacher','Manager','Admin'];
const rejectionReasons=['Fake Person','We Are Off Now','Not a Real Photo'];

app.use('/api/*',cors({origin:(origin,c)=>!origin||origin===c.env.APP_ORIGIN?origin||c.env.APP_ORIGIN:c.env.APP_ORIGIN,allowMethods:['GET','POST','PATCH','DELETE','OPTIONS'],allowHeaders:['Content-Type','Authorization'],exposeHeaders:['ETag']}));
app.onError((error,c)=>{console.error(JSON.stringify({level:'error',message:error.message,path:c.req.path,requestId:c.req.header('cf-ray')}));return c.json({error:'Internal server error'},500)});
app.get('/api/health',c=>c.json({ok:true,service:'whyman-api',version:2}));

async function auth(c:any,next:any){const token=(c.req.header('authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return c.json({error:'Authentication required'},401);const hash=await sha256(token);const row=await c.env.DB.prepare(`SELECT s.id session_id,s.user_id,s.impersonator_user_id,u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.status='Active'`).bind(hash).first<any>();if(!row)return c.json({error:'Invalid or expired session'},401);c.set('session',{id:row.session_id,user_id:row.user_id,impersonator_user_id:row.impersonator_user_id});c.set('user',{id:row.id,student_id:row.student_id,name:row.name,role:row.role,institution:row.institution,stage:row.stage,status:row.status,active_course_id:row.active_course_id,email:row.email,representative_active:row.representative_active});await next()}
function requireRole(...allowed:string[]){return async(c:any,next:any)=>{const user=c.get('user') as User;if(!user||!allowed.includes(user.role))return c.json({error:'Forbidden'},403);await next()}}
async function audit(db:D1Database,actor:string|null,action:string,target?:string,metadata?:unknown){await db.prepare('INSERT INTO audit_logs(actor_id,action,target_id,metadata) VALUES(?,?,?,?)').bind(actor,action,target??null,metadata?JSON.stringify(metadata):null).run()}

app.post('/api/auth/sign-in',async c=>{const body=await c.req.json<{studentId:string;passkey:string}>();if(!body.studentId||!/^[0-9]{6}$/.test(body.passkey||''))return c.json({error:'Student ID and six-digit passkey required'},400);const user=await c.env.DB.prepare(`SELECT * FROM users WHERE student_id=? AND passkey_hash=? AND status='Active'`).bind(body.studentId,await sha256(body.passkey)).first<User>();if(!user)return c.json({error:'Invalid credentials'},401);const token=randomToken();const id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(id,user.id,await sha256(token)).run();await audit(c.env.DB,user.id,'auth.sign_in',user.id);return c.json({token,user:safeUser(user)})});
app.post('/api/auth/sign-out',auth,async c=>{await c.env.DB.prepare('DELETE FROM sessions WHERE id=?').bind((c.get('session') as Session).id).run();return c.json({ok:true})});
app.get('/api/me',auth,c=>c.json({user:safeUser(c.get('user') as User),impersonating:Boolean((c.get('session') as Session).impersonator_user_id)}));

app.post('/api/verification/send',async c=>{const body=await c.req.json<{channel:'email'|'phone';destination:string}>();if(!['email','phone'].includes(body.channel)||!body.destination)return c.json({error:'Invalid verification request'},400);const code=randomDigits(6);await c.env.DB.prepare("DELETE FROM verification_codes WHERE channel=? AND destination=? AND verified_at IS NULL").bind(body.channel,body.destination).run();await c.env.DB.prepare("INSERT INTO verification_codes(id,channel,destination,code_hash,expires_at) VALUES(?,?,?,?,datetime('now','+10 minutes'))").bind(crypto.randomUUID(),body.channel,body.destination,await sha256(code)).run();return c.json({sent:true,developmentCode:code})});
app.post('/api/verification/verify',async c=>{const body=await c.req.json<{channel:'email'|'phone';destination:string;code:string}>();const row=await c.env.DB.prepare("SELECT id FROM verification_codes WHERE channel=? AND destination=? AND code_hash=? AND expires_at>CURRENT_TIMESTAMP AND verified_at IS NULL ORDER BY created_at DESC").bind(body.channel,body.destination,await sha256(body.code||'')).first<{id:string}>();if(!row)return c.json({error:'Invalid or expired code'},400);await c.env.DB.prepare('UPDATE verification_codes SET verified_at=CURRENT_TIMESTAMP WHERE id=?').bind(row.id).run();return c.json({verified:true})});

app.get('/api/institutions',async c=>{const {results}=await c.env.DB.prepare('SELECT id,name,type,representative_user_id FROM institutions ORDER BY name').all();return c.json(results)});
app.get('/api/institution-course-map',async c=>{const {results}=await c.env.DB.prepare('SELECT m.*,c.name course_name FROM institution_stage_courses m JOIN courses c ON c.id=m.course_id ORDER BY institution,stage').all();return c.json(results)});
app.get('/api/courses',async c=>{const institution=c.req.query('institution');const statement=institution?c.env.DB.prepare("SELECT * FROM courses WHERE visibility='Public' OR institution=? ORDER BY name").bind(institution):c.env.DB.prepare('SELECT * FROM courses ORDER BY name');const {results}=await statement.all();return c.json(results)});
app.get('/api/courses/:id',async c=>{const course=await c.env.DB.prepare('SELECT * FROM courses WHERE id=?').bind(c.req.param('id')).first();if(!course)return c.json({error:'Course not found'},404);const [subjects,rooms,posts]=await Promise.all([c.env.DB.prepare('SELECT * FROM subjects WHERE course_id=? ORDER BY name').bind(c.req.param('id')).all(),c.env.DB.prepare('SELECT * FROM study_rooms WHERE course_id=? ORDER BY starts_at').bind(c.req.param('id')).all(),c.env.DB.prepare('SELECT * FROM community_posts WHERE course_id=? ORDER BY created_at DESC LIMIT 30').bind(c.req.param('id')).all()]);return c.json({course,subjects:subjects.results,studyRooms:rooms.results,community:posts.results})});
app.get('/api/subjects/:id',async c=>{const subject=await c.env.DB.prepare('SELECT * FROM subjects WHERE id=?').bind(c.req.param('id')).first();if(!subject)return c.json({error:'Subject not found'},404);const [lectures,attachments]=await Promise.all([c.env.DB.prepare('SELECT * FROM lectures WHERE subject_id=? ORDER BY starts_at DESC').bind(c.req.param('id')).all(),c.env.DB.prepare('SELECT * FROM attachments WHERE subject_id=? ORDER BY uploaded_at DESC').bind(c.req.param('id')).all()]);return c.json({subject,lectures:lectures.results,attachments:attachments.results})});
app.patch('/api/me/active-course',auth,async c=>{const user=c.get('user') as User;const {courseId}=await c.req.json<{courseId:string}>();const course=await c.env.DB.prepare("SELECT id FROM courses WHERE id=? AND (visibility='Public' OR institution=?)").bind(courseId,user.institution).first();if(!course)return c.json({error:'Course is not available to this user'},403);await c.env.DB.batch([c.env.DB.prepare('UPDATE users SET active_course_id=? WHERE id=?').bind(courseId,user.id),c.env.DB.prepare("INSERT OR IGNORE INTO enrollments(id,user_id,course_id) VALUES(?,?,?)").bind(crypto.randomUUID(),user.id,courseId)]);return c.json({activeCourseId:courseId})});

app.post('/api/signup-requests',async c=>{const b=await c.req.json<any>();if(!b.name||!b.fatherName||!b.grandfatherName||!b.dateOfBirth||!b.sex||!b.role||!b.email||!b.phone||!b.photoKey)return c.json({error:'All identity and contact fields are required'},400);if(!roles.slice(0,4).includes(b.role))return c.json({error:'Invalid role'},400);const free=b.accountType==='Free';if(free&&!['Student','Teacher'].includes(b.role))return c.json({error:'Only students and teachers can be free users'},400);if(!free&&(!b.institution||!b.stage))return c.json({error:'Institution and stage are required'},400);const verified=await c.env.DB.prepare("SELECT COUNT(DISTINCT channel) count FROM verification_codes WHERE verified_at IS NOT NULL AND ((channel='email' AND destination=?) OR (channel='phone' AND destination=?))").bind(b.email,b.phone).first<{count:number}>();if((verified?.count||0)<2)return c.json({error:'Email and phone must both be verified'},400);let tier='Admin';if(!free){const representative=await c.env.DB.prepare("SELECT id FROM users WHERE role='Representative Student' AND institution=? AND representative_active=1 AND status='Active' LIMIT 1").bind(b.institution).first();if(b.role!=='Representative Student'||representative)tier='Admin + Representative'}const id=crypto.randomUUID();await c.env.DB.prepare(`INSERT INTO signup_requests(id,name,father_name,grandfather_name,date_of_birth,sex,role,institution,stage,email,phone,photo_key,status,approval_tier,account_type) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,b.name,b.fatherName,b.grandfatherName,b.dateOfBirth,b.sex,b.role,free?null:b.institution,free?null:b.stage,b.email,b.phone,b.photoKey,'Pending',tier,free?'Free':'Institution').run();await queueEmail(c.env.DB,b.email,'Whyman request received',emailShell('Request Submitted','Your signup request is now under review. We will email you when a decision is made.','#0056D2'));return c.json({id,status:'Pending',approvalTier:tier},201)});

app.get('/api/admin/signup-requests',auth,requireRole('Admin','Representative Student'),async c=>{const user=c.get('user') as User;const query=user.role==='Admin'?c.env.DB.prepare('SELECT * FROM signup_requests ORDER BY created_at DESC'):c.env.DB.prepare("SELECT * FROM signup_requests WHERE institution=? AND approval_tier='Admin + Representative' ORDER BY created_at DESC").bind(user.institution);const {results}=await query.all();return c.json(results)});
app.patch('/api/admin/signup-requests/:id',auth,requireRole('Admin','Representative Student'),async c=>{const reviewer=c.get('user') as User;const b=await c.req.json<{decision:'Accept'|'Reject';reason?:string}>();if(!['Accept','Reject'].includes(b.decision))return c.json({error:'Invalid decision'},400);if(b.decision==='Reject'&&!rejectionReasons.includes(b.reason||''))return c.json({error:'Select a valid rejection reason'},400);const request=await c.env.DB.prepare('SELECT * FROM signup_requests WHERE id=?').bind(c.req.param('id')).first<any>();if(!request)return c.json({error:'Request not found'},404);if(reviewer.role==='Representative Student'&&request.institution!==reviewer.institution)return c.json({error:'Request outside your institution'},403);if(b.decision==='Reject'){await c.env.DB.prepare("UPDATE signup_requests SET status='Rejected',rejection_reason=?,reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.reason,reviewer.id,request.id).run();await queueEmail(c.env.DB,request.email,'Whyman application update',emailShell('Application Not Approved',`Reason: ${escapeHtml(b.reason||'Not approved')}. You may contact support and reapply with corrected information.`,'#D93025'));await audit(c.env.DB,reviewer.id,'signup.reject',request.id,{reason:b.reason});return c.json({status:'Rejected'})}
if(reviewer.role==='Representative Student'){await c.env.DB.prepare('UPDATE signup_requests SET representative_approved=1,reviewed_by=? WHERE id=?').bind(reviewer.id,request.id).run();return c.json({status:'Pending Admin Approval'})}
const needsRep=request.approval_tier==='Admin + Representative';if(needsRep&&!request.representative_approved)return c.json({error:'Representative approval is still required'},409);const passkey=randomDigits(6);const prefix=request.role==='Teacher'?'TCH':request.role==='Manager'?'MGR':request.role==='Representative Student'?'REP':'STU';const studentId=`${prefix}-${new Date().getUTCFullYear()}-${randomDigits(5)}`;const userId=crypto.randomUUID();let activeCourse:string|null=null;if(request.account_type==='Institution'){const mapping=await c.env.DB.prepare('SELECT course_id FROM institution_stage_courses WHERE institution=? AND stage=?').bind(request.institution,request.stage).first<{course_id:string}>();activeCourse=mapping?.course_id||null}
await c.env.DB.batch([c.env.DB.prepare(`INSERT INTO users(id,student_id,name,role,institution,stage,status,active_course_id,email,phone,photo_key,passkey_hash,representative_active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(userId,studentId,request.name,request.role,request.institution,request.stage,'Active',activeCourse,request.email,request.phone,request.photo_key,await sha256(passkey),request.role==='Representative Student'?1:0),c.env.DB.prepare("UPDATE signup_requests SET status='Active',admin_approved=1,student_id=?,passkey_hash=?,reviewed_by=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?").bind(studentId,await sha256(passkey),reviewer.id,request.id)]);if(activeCourse)await c.env.DB.prepare('INSERT OR IGNORE INTO enrollments(id,user_id,course_id) VALUES(?,?,?)').bind(crypto.randomUUID(),userId,activeCourse).run();if(request.role==='Representative Student'&&request.institution)await c.env.DB.prepare('UPDATE institutions SET representative_user_id=? WHERE name=?').bind(userId,request.institution).run();await queueEmail(c.env.DB,request.email,"You're In! Welcome to Whyman",approvalEmail(request.name,studentId,passkey));await audit(c.env.DB,reviewer.id,'signup.accept',request.id,{userId,studentId,activeCourse});return c.json({status:'Active',studentId,passkey,activeCourseId:activeCourse})});

app.get('/api/admin/users',auth,requireRole('Admin'),async c=>{const {results}=await c.env.DB.prepare('SELECT id,student_id,name,role,institution,stage,status,active_course_id,email,created_at FROM users ORDER BY created_at DESC').all();return c.json(results)});
app.post('/api/admin/impersonate/:userId',auth,requireRole('Admin'),async c=>{const admin=c.get('user') as User;const target=await c.env.DB.prepare("SELECT id FROM users WHERE id=? AND status='Active'").bind(c.req.param('userId')).first<{id:string}>();if(!target)return c.json({error:'User not found'},404);const token=randomToken();await c.env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,impersonator_user_id,expires_at) VALUES(?,?,?,?,datetime('now','+2 hours'))").bind(crypto.randomUUID(),target.id,await sha256(token),admin.id).run();await audit(c.env.DB,admin.id,'admin.impersonate',target.id);return c.json({token})});
app.post('/api/admin/return',auth,async c=>{const session=c.get('session') as Session;if(!session.impersonator_user_id)return c.json({error:'Not impersonating'},400);const token=randomToken();await c.env.DB.batch([c.env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(session.id),c.env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(crypto.randomUUID(),session.impersonator_user_id,await sha256(token))]);return c.json({token})});

app.post('/api/course-creation-requests',auth,async c=>{const user=c.get('user') as User;const b=await c.req.json<{title:string;visibility:'Public'|'Institution';institution?:string;stage?:string;donationId?:string}>();if(!b.title||!['Public','Institution'].includes(b.visibility))return c.json({error:'Invalid course request'},400);if(user.role!=='Representative Student'){if(!b.donationId)return c.json({error:'A $5 donation is required'},402);const donation=await c.env.DB.prepare("SELECT id FROM donations WHERE id=? AND user_id=? AND amount_cents>=500 AND status='Completed'").bind(b.donationId,user.id).first();if(!donation)return c.json({error:'Valid completed $5 donation required'},402)}const id=crypto.randomUUID();await c.env.DB.prepare('INSERT INTO course_creation_requests(id,creator_user_id,title,visibility,institution,stage,donation_id,status) VALUES(?,?,?,?,?,?,?,?)').bind(id,user.id,b.title,b.visibility,b.institution??null,b.stage??null,b.donationId??null,'Pending').run();return c.json({id,status:'Pending'},201)});
app.post('/api/donations',auth,async c=>{const user=c.get('user') as User;const b=await c.req.json<{amountCents:number;purpose:string}>();if(!Number.isInteger(b.amountCents)||b.amountCents<100)return c.json({error:'Invalid donation amount'},400);const id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO donations(id,user_id,amount_cents,purpose,status) VALUES(?,?,?,?,?)").bind(id,user.id,b.amountCents,b.purpose,'Completed').run();return c.json({id,status:'Completed'},201)});
app.get('/api/jobs',async c=>{const {results}=await c.env.DB.prepare("SELECT * FROM jobs WHERE status='Open' ORDER BY created_at DESC").all();return c.json(results)});
app.get('/api/volunteer-programs',async c=>{const {results}=await c.env.DB.prepare("SELECT * FROM volunteer_programs WHERE status='Open' ORDER BY title").all();return c.json(results)});
app.get('/api/notifications',auth,async c=>{const {results}=await c.env.DB.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50').bind((c.get('user') as User).id).all();return c.json(results)});
app.get('/api/admin/email-outbox',auth,requireRole('Admin'),async c=>{const {results}=await c.env.DB.prepare('SELECT id,recipient,subject,status,created_at,sent_at FROM email_outbox ORDER BY created_at DESC LIMIT 100').all();return c.json(results)});

app.post('/api/uploads',async c=>{const length=Number(c.req.header('content-length')||0);if(length>10*1024*1024)return c.json({error:'Maximum upload size is 10 MB'},413);if(!c.req.raw.body)return c.json({error:'Missing file body'},400);const contentType=c.req.header('content-type')||'application/octet-stream';const allowed=['image/jpeg','image/png','image/webp','application/pdf'];if(!allowed.includes(contentType))return c.json({error:'Unsupported file type'},415);const key=`uploads/${new Date().getUTCFullYear()}/${crypto.randomUUID()}`;await c.env.FILES.put(key,c.req.raw.body,{httpMetadata:{contentType},customMetadata:{uploadedAt:new Date().toISOString()}});return c.json({key,url:`/api/files/${key}`},201)});
app.get('/api/files/:key{.+}',async c=>{const object=await c.env.FILES.get(c.req.param('key'),{range:c.req.raw.headers});if(!object)return c.json({error:'Not found'},404);const headers=new Headers();object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('cache-control','private, max-age=3600');return new Response('body'in object?object.body:null,{status:'body'in object?200:412,headers})});

function safeUser(u:User){return{id:u.id,studentId:u.student_id,name:u.name,role:u.role,institution:u.institution,stage:u.stage,activeCourseId:u.active_course_id,email:u.email,representativeActive:Boolean(u.representative_active)}}
function randomDigits(length:number){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);return String(bytes[0]%10**length).padStart(length,'0')}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(value:string){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')}
async function queueEmail(db:D1Database,recipient:string,subject:string,html:string){await db.prepare('INSERT INTO email_outbox(id,recipient,subject,html) VALUES(?,?,?,?)').bind(crypto.randomUUID(),recipient,subject,html).run()}
function emailShell(title:string,body:string,color:string){return`<!doctype html><html><body style="margin:0;background:#F0F2F5;font-family:Inter,Arial,sans-serif"><table width="100%"><tr><td align="center" style="padding:32px"><table width="600" style="max-width:100%;background:#fff;border-radius:18px;overflow:hidden"><tr><td style="padding:22px 28px;background:#0056D2;color:#fff;font-weight:800;font-size:20px">W · Whyman</td></tr><tr><td style="padding:34px 28px"><h1 style="margin:0 0 16px;color:${color};font-size:28px">${title}</h1><p style="color:#65676B;line-height:1.7">${body}</p><a href="#" style="display:inline-block;margin-top:18px;padding:14px 20px;border-radius:14px;background:#0056D2;color:#fff;text-decoration:none;font-weight:700">Open Whyman</a></td></tr><tr><td style="padding:18px 28px;background:#F8F9FB;color:#9EA3AA;font-size:12px">Whyman Learning Network · Support · Privacy</td></tr></table></td></tr></table></body></html>`}
function approvalEmail(name:string,id:string,passkey:string){return emailShell("You're In!",`Welcome ${escapeHtml(name)}. Your account has been approved.<div style="margin:22px 0;padding:18px;border-radius:14px;background:#E8F0FE;font-family:monospace"><strong>Student ID</strong><br>${id}<br><br><strong>Passkey</strong><br><span style="font-size:26px;letter-spacing:8px">${passkey}</span></div>Keep this passkey private.`,'#00A86B')}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]||ch))}
export default app;
