PRAGMA foreign_keys=ON;
ALTER TABLE users ADD COLUMN email TEXT;
ALTER TABLE users ADD COLUMN phone TEXT;
ALTER TABLE users ADD COLUMN photo_key TEXT;
ALTER TABLE users ADD COLUMN passkey_hash TEXT;
ALTER TABLE users ADD COLUMN representative_active INTEGER NOT NULL DEFAULT 0;
ALTER TABLE signup_requests ADD COLUMN father_name TEXT;
ALTER TABLE signup_requests ADD COLUMN grandfather_name TEXT;
ALTER TABLE signup_requests ADD COLUMN date_of_birth TEXT;
ALTER TABLE signup_requests ADD COLUMN sex TEXT;
ALTER TABLE signup_requests ADD COLUMN account_type TEXT NOT NULL DEFAULT 'Institution';
ALTER TABLE signup_requests ADD COLUMN admin_approved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE signup_requests ADD COLUMN representative_approved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE signup_requests ADD COLUMN reviewed_by TEXT;
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,impersonator_user_id TEXT,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token_hash);
CREATE TABLE IF NOT EXISTS institution_stage_courses(id TEXT PRIMARY KEY,institution TEXT NOT NULL,stage TEXT NOT NULL,course_id TEXT NOT NULL,UNIQUE(institution,stage),FOREIGN KEY(course_id) REFERENCES courses(id));
CREATE TABLE IF NOT EXISTS enrollments(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,course_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Active',progress INTEGER NOT NULL DEFAULT 0,enrolled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,course_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS lectures(id TEXT PRIMARY KEY,subject_id TEXT NOT NULL,title TEXT NOT NULL,starts_at TEXT NOT NULL,room_or_link TEXT,duration_minutes INTEGER,recording_key TEXT,status TEXT NOT NULL DEFAULT 'Upcoming',FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS attachments(id TEXT PRIMARY KEY,subject_id TEXT NOT NULL,name TEXT NOT NULL,file_key TEXT NOT NULL,mime_type TEXT,size_bytes INTEGER,uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS study_rooms(id TEXT PRIMARY KEY,course_id TEXT NOT NULL,name TEXT NOT NULL,host_user_id TEXT,starts_at TEXT,capacity INTEGER NOT NULL DEFAULT 12,status TEXT NOT NULL DEFAULT 'Open',FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS community_posts(id TEXT PRIMARY KEY,course_id TEXT NOT NULL,author_user_id TEXT,title TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS donations(id TEXT PRIMARY KEY,user_id TEXT,amount_cents INTEGER NOT NULL,currency TEXT NOT NULL DEFAULT 'USD',purpose TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS course_creation_requests(id TEXT PRIMARY KEY,creator_user_id TEXT NOT NULL,title TEXT NOT NULL,visibility TEXT NOT NULL,institution TEXT,stage TEXT,donation_id TEXT,status TEXT NOT NULL DEFAULT 'Draft',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,title TEXT NOT NULL,organization TEXT NOT NULL,location TEXT,employment_type TEXT,tags TEXT,status TEXT NOT NULL DEFAULT 'Open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS job_applications(id TEXT PRIMARY KEY,job_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Applied',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS volunteer_programs(id TEXT PRIMARY KEY,title TEXT NOT NULL,organization TEXT NOT NULL,hours_target INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'Open');
CREATE TABLE IF NOT EXISTS volunteer_hours(id TEXT PRIMARY KEY,program_id TEXT NOT NULL,user_id TEXT NOT NULL,hours REAL NOT NULL,verified INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'Info',read_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS email_outbox(id TEXT PRIMARY KEY,recipient TEXT NOT NULL,subject TEXT NOT NULL,html TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Queued',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,sent_at TEXT);
CREATE TABLE IF NOT EXISTS verification_codes(id TEXT PRIMARY KEY,channel TEXT NOT NULL,destination TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at TEXT NOT NULL,verified_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO institution_stage_courses(id,institution,stage,course_id) VALUES('map-baghdad-2','Baghdad University','Stage 2','c1');
INSERT OR IGNORE INTO lectures(id,subject_id,title,starts_at,room_or_link,duration_minutes,status) VALUES('l1','s1','Graph Algorithms','2026-08-06T10:00:00Z','Lab 4',90,'Upcoming'),('l2','s2','SQL Joins Workshop','2026-08-09T12:30:00Z','Room B12',75,'Upcoming');
INSERT OR IGNORE INTO jobs(id,title,organization,location,employment_type,tags) VALUES('j1','Junior Frontend Intern','Nahrain Labs','Baghdad','Internship','React,TypeScript'),('j2','Community Coordinator','Learn Iraq','Remote','Part-time','Community,Education');
INSERT OR IGNORE INTO volunteer_programs(id,title,organization,hours_target) VALUES('v1','Digital Literacy Weekend','Whyman Foundation',12),('v2','Campus Welcome Team','Baghdad University',8);
