import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Cloud,Eye,EyeOff,GraduationCap,ImagePlus,KeyRound,Loader2,LockKeyhole,Phone,School,ShieldCheck,UserRound,X} from 'lucide-react';
import {NavExperience} from './NavExperience';
import {api,ApiError,ApiRole,SessionUser,SignupPayload} from './lib/api';

type Mode='welcome'|'signin'|'signup'|'submitted';
type Role=Exclude<ApiRole,'Admin'>;
type Form={name:string;fatherName:string;grandfatherName:string;dateOfBirth:string;sex:string;role:Role;accountType:'Free'|'Institution';institution:string;stage:string;email:string;phone:string;photo:File|null;photoKey:string};
const initial:Form={name:'',fatherName:'',grandfatherName:'',dateOfBirth:'',sex:'',role:'Student',accountType:'Free',institution:'',stage:'',email:'',phone:'',photo:null,photoKey:''};
const stages=['Stage 1','Stage 2','Stage 3','Stage 4','Stage 5','Stage 6'];

export function EmailOnlyApp(){
  const[mode,setMode]=useState<Mode>('welcome');
  const[user,setUser]=useState<SessionUser|null>(null);
  const[checking,setChecking]=useState(true);
  useEffect(()=>{if(!api.hasSession()){setChecking(false);return}api.me().then(r=>setUser(r.user)).catch(()=>api.clearSession()).finally(()=>setChecking(false))},[]);
  if(checking)return <div className="pa-splash"><div className="pa-mark">W</div><Loader2 className="spin"/><p>Opening Whyman…</p></div>;
  if(user)return <div className="pa-session"><div className="pa-sessionbar"><span><Cloud size={15}/> Signed in as <b>{user.name}</b></span><button onClick={()=>api.signOut().finally(()=>{setUser(null);setMode('welcome')})}>Sign out</button></div><NavExperience/></div>;
  return <div className="pa-page"><Header join={()=>setMode('signup')} signIn={()=>setMode('signin')}/>{mode==='welcome'&&<Welcome join={()=>setMode('signup')} signIn={()=>setMode('signin')} demo={()=>setUser({id:'demo',student_id:'DEMO',name:'Tary Avy',role:'Student',institution:'Baghdad University',stage:'Stage 2',status:'Active',active_course_id:'c1'})}/>} {mode==='signin'&&<SignIn close={()=>setMode('welcome')} success={setUser}/>} {mode==='signup'&&<Signup close={()=>setMode('welcome')} submitted={()=>setMode('submitted')}/>} {mode==='submitted'&&<Submitted home={()=>setMode('welcome')}/>}</div>;
}

function Header({join,signIn}:{join:()=>void;signIn:()=>void}){return <header className="pa-header"><Brand/><div><button className="pa-link" onClick={signIn}>Sign in</button><button className="pa-primary" onClick={join}>Join Us</button></div></header>}
function Brand(){return <div className="pa-brand"><div className="pa-mark">W</div><span><b>Whyman</b><small>Learning Network</small></span></div>}
function Welcome({join,signIn,demo}:{join:()=>void;signIn:()=>void;demo:()=>void}){return <main className="pa-welcome"><section className="pa-hero"><div><span className="pa-pill"><ShieldCheck/>Verified learning community</span><h1>Learn boldly.<br/>Grow with proof.</h1><p>One trusted place for education, identity, opportunity, volunteering, donations, and community.</p><div className="pa-actions"><button className="pa-primary large" onClick={join}>Create your account <ArrowRight/></button><button className="pa-secondary large" onClick={demo}>Explore demo</button></div><button className="pa-text" onClick={signIn}>Already approved? Sign in with your ID and passkey</button></div><article className="pa-id"><header><div className="pa-mark inverse">W</div><b>DIGITAL ID</b></header><main><i>TA</i><div><small>STUDENT</small><h3>Tary Avy</h3><p>Computer Science · Stage 2</p></div></main><footer><code>STU-2026-004821</code><span>VERIFIED</span></footer></article></section><section className="pa-stats">{[['128','Institutions'],['6,204','Credentials'],['$42k','Donated'],['99%','Verification']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section></main>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="pa-backdrop"><section className="pa-modal"><button className="pa-close" onClick={close} aria-label="Close"><X/></button>{children}</section></div>}

function SignIn({close,success}:{close:()=>void;success:(u:SessionUser)=>void}){
  const[id,setId]=useState(''),[pass,setPass]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{success(await api.signIn(id.trim(),pass))}catch(err){setError(err instanceof ApiError?err.message:'Unable to sign in')}finally{setBusy(false)}}
  return <Modal close={close}><div className="pa-authicon"><LockKeyhole/></div><span className="pa-kicker">Welcome back</span><h2>Sign in to Whyman</h2><p className="pa-lead">Use the ID and six-digit passkey sent after approval.</p><form onSubmit={submit} className="pa-form"><label>Student ID<div className="pa-input"><UserRound/><input value={id} onChange={e=>setId(e.target.value)} placeholder="STU-2026-00001" autoCapitalize="characters"/></div></label><label>Six-digit passkey<div className="pa-input"><KeyRound/><input value={pass} onChange={e=>setPass(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="••••••" type={show?'text':'password'} inputMode="numeric"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="pa-error">{error}</div>}<button className="pa-primary wide" disabled={busy||!id||pass.length!==6}>{busy?<Loader2 className="spin"/>:<LockKeyhole/>} Sign in</button></form></Modal>;
}

function Signup({close,submitted}:{close:()=>void;submitted:()=>void}){
  const[step,setStep]=useState(0),[form,setForm]=useState<Form>(initial),[institutions,setInstitutions]=useState<string[]>(['Baghdad University','Basra University','University of Mosul']),[emailVerified,setEmailVerified]=useState(false),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
  useEffect(()=>{api.institutions().then(rows=>rows.length&&setInstitutions(rows.map(row=>row.name))).catch(()=>{})},[]);
  useEffect(()=>{if(['Representative Student','Manager'].includes(form.role)&&form.accountType==='Free')setForm(current=>({...current,accountType:'Institution'}))},[form.role]);
  const valid=useMemo(()=>{if(step===0)return Boolean(form.name&&form.fatherName&&form.grandfatherName&&form.dateOfBirth&&form.sex&&form.photo);if(step===1)return Boolean(form.role);if(step===2)return form.accountType==='Free'||Boolean(form.institution&&form.stage);return Boolean(emailVerified&&form.phone.trim())},[step,form,emailVerified]);
  async function sendCode(){setBusy(true);setError('');try{await api.sendVerificationCode('email',form.email.trim());setSent(true)}catch(err){setError(err instanceof ApiError?err.message:'Could not send email')}finally{setBusy(false)}}
  async function verify(){setBusy(true);setError('');try{await api.verifyCode('email',form.email.trim(),code);setEmailVerified(true)}catch(err){setError(err instanceof ApiError?err.message:'Invalid or expired code')}finally{setBusy(false)}}
  async function finish(){setBusy(true);setError('');try{const photoKey=form.photoKey||(form.photo?await api.upload(form.photo):'');const payload:SignupPayload={name:form.name,fatherName:form.fatherName,grandfatherName:form.grandfatherName,dateOfBirth:form.dateOfBirth,sex:form.sex,role:form.role,accountType:form.accountType,institution:form.accountType==='Institution'?form.institution:undefined,stage:form.accountType==='Institution'?form.stage:undefined,email:form.email.trim(),phone:form.phone.trim(),photoKey};await api.createSignupRequest(payload);submitted()}catch(err){setError(err instanceof ApiError?err.message:'Could not submit request')}finally{setBusy(false)}}
  return <Modal close={close}><div className="pa-progress"><span style={{width:`${(step+1)*25}%`}}/></div><div className="pa-stepcount">Step {step+1} of 4</div>{step===0&&<Identity form={form} setForm={setForm}/>} {step===1&&<RoleStep form={form} setForm={setForm}/>} {step===2&&<InstitutionStep form={form} setForm={setForm} institutions={institutions}/>} {step===3&&<EmailVerification form={form} setForm={setForm} verified={emailVerified} code={code} setCode={setCode} sent={sent} send={sendCode} verify={verify} busy={busy}/>} {error&&<div className="pa-error">{error}</div>}<div className="pa-navactions">{step>0?<button className="pa-secondary" onClick={()=>setStep(value=>value-1)}><ArrowLeft/> Back</button>:<button className="pa-secondary" onClick={close}>Cancel</button>}{step<3?<button className="pa-primary" disabled={!valid} onClick={()=>setStep(value=>value+1)}>Next <ArrowRight/></button>:<button className="pa-primary" disabled={!valid||busy} onClick={finish}>{busy?<Loader2 className="spin"/>:<Check/>} Send request</button>}</div></Modal>;
}

function Identity({form,setForm}:{form:Form;setForm:React.Dispatch<React.SetStateAction<Form>>}){const set=(key:keyof Form,value:unknown)=>setForm(current=>({...current,[key]:value}));return <><span className="pa-kicker">Your identity</span><h2>Tell us who you are</h2><p className="pa-lead">All fields and a clear real photo are required.</p><div className="pa-grid"><Field label="Name" value={form.name} set={value=>set('name',value)}/><Field label="Father’s name" value={form.fatherName} set={value=>set('fatherName',value)}/><Field label="Grandfather’s name" value={form.grandfatherName} set={value=>set('grandfatherName',value)}/><label>Date of birth<input type="date" value={form.dateOfBirth} onChange={event=>set('dateOfBirth',event.target.value)}/></label><label>Sex<select value={form.sex} onChange={event=>set('sex',event.target.value)}><option value="">Select</option><option>Female</option><option>Male</option></select></label><label className="pa-upload"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>set('photo',event.target.files?.[0]||null)}/><span><ImagePlus/>{form.photo?form.photo.name:'Import real photo'}</span></label></div></>}
function Field({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <label>{label}<input value={value} onChange={event=>set(event.target.value)}/></label>}
function RoleStep({form,setForm}:{form:Form;setForm:React.Dispatch<React.SetStateAction<Form>>}){const roles:Role[]=['Student','Representative Student','Teacher','Manager'];return <><span className="pa-kicker">Account role</span><h2>How will you use Whyman?</h2><p className="pa-lead">Teacher and Manager workspaces are prepared but currently inactive.</p><div className="pa-choices">{roles.map(role=><button className={form.role===role?'selected':''} onClick={()=>setForm(current=>({...current,role}))} key={role}><GraduationCap/><b>{role}</b><span>{role==='Student'?'Learn, connect, and grow':role==='Representative Student'?'Manage institution submissions':role==='Teacher'?'Teaching workspace coming soon':'Management workspace coming soon'}</span></button>)}</div></>}
function InstitutionStep({form,setForm,institutions}:{form:Form;setForm:React.Dispatch<React.SetStateAction<Form>>;institutions:string[]}){const forced=['Representative Student','Manager'].includes(form.role);return <><span className="pa-kicker">Learning context</span><h2>{forced?'Select your institution':'Free user or institution?'}</h2><p className="pa-lead">Institution accounts are assigned to their mapped course after approval.</p>{!forced&&<div className="pa-segment"><button className={form.accountType==='Free'?'active':''} onClick={()=>setForm(current=>({...current,accountType:'Free',institution:'',stage:''}))}>Free user</button><button className={form.accountType==='Institution'?'active':''} onClick={()=>setForm(current=>({...current,accountType:'Institution'}))}>Specific institution</button></div>}{form.accountType==='Institution'?<div className="pa-grid one"><label>University / College<select value={form.institution} onChange={event=>setForm(current=>({...current,institution:event.target.value}))}><option value="">Select institution</option>{institutions.map(item=><option key={item}>{item}</option>)}</select></label><label>Stage<select value={form.stage} onChange={event=>setForm(current=>({...current,stage:event.target.value}))}><option value="">Select stage</option>{stages.map(item=><option key={item}>{item}</option>)}</select></label></div>:<div className="pa-note"><School/><div><b>Public-course access</b><span>Free users can join Public courses only. Only Students and Teachers are eligible.</span></div></div>}</>}

function EmailVerification({form,setForm,verified,code,setCode,sent,send,verify,busy}:{form:Form;setForm:React.Dispatch<React.SetStateAction<Form>>;verified:boolean;code:string;setCode:(value:string)=>void;sent:boolean;send:()=>void;verify:()=>void;busy:boolean}){return <><span className="pa-kicker">Contact verification</span><h2>Verify your email</h2><p className="pa-lead">We will email a six-digit code. Your phone number is saved for your profile but is not verified.</p><div className={`pa-verify ${verified?'done':''}`}><div className="pa-input"><span>@</span><input type="email" value={form.email} onChange={event=>setForm(current=>({...current,email:event.target.value}))} placeholder="name@example.com" disabled={verified}/></div>{verified?<span className="pa-verified"><Check/> Email verified</span>:<><button className="pa-secondary" disabled={busy||!form.email.trim()} onClick={send}>{busy?<Loader2 className="spin"/>:'Send email code'}</button>{sent&&<div className="pa-code"><input value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" inputMode="numeric"/><button disabled={busy||code.length!==6} onClick={verify}>Verify</button></div>}</>}</div><div className="pa-note"><Phone/><div><b>Phone number</b><span>Stored in your account; SMS verification is not required.</span></div></div><div className="pa-input"><Phone/><input type="tel" value={form.phone} onChange={event=>setForm(current=>({...current,phone:event.target.value}))} placeholder="+964 7xx xxx xxxx"/></div></>}
function Submitted({home}:{home:()=>void}){return <main className="pa-submitted"><div className="pa-success"><Check/></div><span className="pa-kicker">Request submitted</span><h1>Your application is under review.</h1><p>We saved your request in Whyman. Approval or rejection updates will be sent to your verified email.</p><button className="pa-primary" onClick={home}>Return to home</button></main>}
